name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install nbconvert
        run: pip install nbconvert

      - name: Convert notebooks to Python scripts
        run: find . -name "*.ipynb" -exec jupyter nbconvert --to script {} \;

      - name: Install Serverless Framework v3.38.0
        run: |
          npm install -g serverless@3.38.0
          npm install serverless-python-requirements

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Deploy to AWS Lambda
        run: serverless deploy
